<?php
/**
*
* Kiss Portal extension for the phpBB Forum Software package.
*
* @copyright (c) 2022 Michael O’Toole <http://www.phpbbireland.com>
* @license GNU General Public License, version 2 (GPL-2.0)
*
*/

namespace phpbbireland\portal\migrations\v10x;

class release_1_0_0 extends \phpbb\db\migration\migration
{
	public function effectively_installed()
	{
		return isset($this->config['portal_mod_version']) && version_compare($this->config['portal_mod_version'], '1.0.0', '>=');
	}

	static public function depends_on()
	{
		return ['\phpbb\db\migration\data\v310\dev'];
	}

	public function update_data()
	{
		return [
			['config.add', ['portal_enabled', 1]],
			['config.add', ['blocks_enabled', 1]],
			['config.add', ['portal_version', '1.0.0']],
			['config.add', ['portal_build', '310-004']],
			['config.add', ['blocks_width', '190']],

			['permission.add', ['a_k_portal']],
			['permission.add', ['u_k_portal']],

//			['permission.role_add', ['Administer Portal', 'a_', 'portal']],

			['permission.permission_set', ['ROLE_ADMIN_FULL', 'a_k_portal']],
			['permission.permission_set', ['REGISTERED', 'u_k_portal', 'group']],

			['module.add', [
				'acp',
				'',
				'ACP_PORTAL_TITLE',
			]],

			['module.add', [
				'acp',
				'ACP_PORTAL_TITLE',
				'ACP_CONFIG_TITLE',
			]],
			['module.add', [
				'acp',
				'ACP_PORTAL_TITLE',
				'ACP_BLOCKS_TITLE',
			]],
			['module.add', [
				'acp',
				'ACP_PORTAL_TITLE',
				'ACP_MENUS_TITLE',
			]],

			['module.add', [
				'acp',
				'ACP_PORTAL_TITLE',
				'ACP_PAGES_TITLE',
			]],
			['module.add', [
				'acp',
				'ACP_PORTAL_TITLE',
				'ACP_RESOURCES_TITLE',
			]],
			['module.add', [
				'acp',
				'ACP_PORTAL_TITLE',
				'ACP_VARS_TITLE',
			]],

			['module.add', [
				'acp',
				'ACP_CONFIG_TITLE',
				[
					'module_basename' => '\phpbbireland\portal\acp\config_module',
					'modes'           => ['config_portal'],
				],
			]],

			['module.add', [
				'acp',
				'ACP_BLOCKS_TITLE',
				[
					'module_basename' => '\phpbbireland\portal\acp\blocks_module',
					'modes'           => ['add', 'edit', 'delete', 'up', 'down', 'reindex', 'L', 'C', 'R', 'manage', 'reset'],
				],
			]],
			['module.add', [
				'acp',
				'ACP_MENUS_TITLE',
				[
					'module_basename' => '\phpbbireland\portal\acp\menus_module',
					'modes'           => ['add', 'nav', 'sub', 'link', 'edit', 'delete', 'up', 'down', 'all', 'unalloc'],
				],
			]],

			['module.add', [
				'acp',
				'ACP_PAGES_TITLE',
				[
					'module_basename' => '\phpbbireland\portal\acp\pages_module',
					'modes'           => ['add', 'delete', 'land', 'manage'],
				],
			]],

			['module.add', [
				'acp',
				'ACP_RESOURCES_TITLE',
				[
					'module_basename' => '\phpbbireland\portal\acp\resources_module',
					'modes'           => ['select'],
				],
			]],

			['module.add', [
				'acp',
				'ACP_VARS_TITLE',
				[
					'module_basename' => '\phpbbireland\portal\acp\vars_module',
					'modes'           => ['manage'],
				],
			]],

			['module.add', [
				'ucp',
				'0',
				'UCP_PORTAL_TITLE',
			]],

			['module.add', [
				'ucp',
				'UCP_PORTAL_TITLE',
				[
					'module_basename'	=> '\phpbbireland\portal\ucp\portal_module',
					'modes'				=> ['info', 'arrange', 'edit', 'delete', 'width'],
					'module_auth'		=> 'acl_u_k_portal',
				],
			]],

			['config.add', ['portal_mod_version', '1.0.0']],

			['custom', [[$this, 'seed_db']]],
		];
	}

	public function update_schema()
	{
		return [

			'add_tables' => [
				$this->table_prefix . 'k_config' => [
					'COLUMNS' => [
						'config_name'		=> ['VCHAR', ''],
						'config_value'		=> ['VCHAR', ''],
						'is_dynamic'		=> ['BOOL', '0'],
					],
					'PRIMARY_KEY'	=> 'config_name',
					'KEYS'			=> ['is_dynamic'	=> ['INDEX', 'is_dynamic'],
					],
				],
				$this->table_prefix . 'k_vars' => [
					'COLUMNS' => [
						'config_name'		=> ['VCHAR', ''],
						'config_value'		=> ['VCHAR', ''],
					],
					'PRIMARY_KEY'	=> 'config_name',
				],
				$this->table_prefix . 'k_blocks' => [
					'COLUMNS' => [
						'id'                => ['UINT', null, 'auto_increment'],
						'ndx'               => ['UINT', '0'],
						'title'             => ['VCHAR:50', ''],
						'position'          => ['CHAR:1', 'L'],
						'type'              => ['CHAR:1', 'H'],
						'active'            => ['BOOL', '1'],
						'html_file_name'    => ['VCHAR', ''],
						'var_file_name'     => ['VCHAR', 'none.gif'],
						'img_file_name'     => ['VCHAR', 'none.gif'],
						'view_all'          => ['BOOL', '1'],
						'view_groups'       => ['VCHAR:100', ''],
						'view_pages'        => ['VCHAR:100', ''],
						'groups'            => ['UINT', '0'],
						'scroll'            => ['BOOL', '0'],
						'block_height'      => ['USINT', '0'],
						'has_vars'          => ['BOOL', '0'],
						'is_static'         => ['BOOL', '0'],
						'minimod_based'     => ['BOOL', '0'],
						'mod_block_id'      => ['UINT', '0'],
						'block_cache_time'  => ['UINT', '600'],
					],
					'PRIMARY_KEY'  => 'id',
				],
				$this->table_prefix . 'k_menus' => [
					'COLUMNS' => [
						'm_id'			=> ['UINT', null, 'auto_increment'],
						'ndx'			=> ['UINT', '0'],
						'menu_type'		=> ['USINT', '0'],
						'name'			=> ['VCHAR:50', ''],
						'link_to'		=> ['VCHAR', ''],
						'extern'		=> ['BOOL', '0'],
						'menu_icon'		=> ['VCHAR:30', 'none.gif'],
						'append_sid'	=> ['BOOL', '1'],
						'append_uid'	=> ['BOOL', '0'],
						'view_all'		=> ['BOOL', '1'],
						'view_groups'	=> ['VCHAR:100', ''],
						'soft_hr'		=> ['BOOL', '0'],
						'sub_heading'	=> ['BOOL', '0'],
					],
					'PRIMARY_KEY'  => 'm_id',
				],
				$this->table_prefix . 'k_pages' => [
					'COLUMNS' => [
						'page_id'	=> ['UINT', null, 'auto_increment'],
						'page_name'	=> ['VCHAR_UNI:100', ''],
					],
					'PRIMARY_KEY'	=> 'page_id',
				],
				$this->table_prefix . 'k_resources' => [
					'COLUMNS' => [
						'id'	=> ['UINT', null, 'auto_increment'],
						'word'	=> ['VCHAR:50', ''],
						'type'	=> ['CHAR:1', 'V'],
					],
					'PRIMARY_KEY'	=> 'id',
				],
			],

			'add_columns'    => [
				$this->table_prefix . 'users' => [
					'user_left_blocks'    => ['VCHAR:255', ''],
					'user_center_blocks'  => ['VCHAR:255', ''],
					'user_right_blocks'   => ['VCHAR:255', ''],
				],
			],
		];
	}

	public function revert_schema()
	{
		return [
			'drop_tables'	=> [
				$this->table_prefix . 'k_config',
				$this->table_prefix . 'k_blocks',
				$this->table_prefix . 'k_menus',
				$this->table_prefix . 'k_pages',
				$this->table_prefix . 'k_resources',
				$this->table_prefix . 'k_vars',
			],
			'drop_columns' => [
				$this->table_prefix . 'users' => [
					'user_left_blocks',
					'user_center_blocks',
					'user_right_blocks',
				],
			],
			['config.remove', ['portal_enabled']],
			['config.remove', ['blocks_enabled']],
			['config.remove', ['portal_version']],
			['config.remove', ['portal_build']],
			['config.remove', ['blocks_width']],

			['permission.remove', ['a_k_portal']],
			['permission.remove', ['u_k_portal']],
		];
	}

	public function seed_db()
	{
		$blocks_sql = [
			[
				'ndx'			=> '1',
				'title'			=> 'Site Navigator',
				'position'		=> 'L',
				'type'			=> 'H',
				'active'		=> '1',
				'html_file_name'=> 'block_menus_nav.html',
				'var_file_name'	=> '',
				'img_file_name'	=> 'menu.png',
				'view_all'		=> '1',
				'view_groups'	=> '0',
				'view_pages'	=> '1,2,3,4,5,6,7,8,9,11,12,13,14',
				'groups'		=> '0',
				'scroll'		=> '0',
				'block_height'	=> '0',
				'has_vars'		=> '0',
				'minimod_based'	=> '0',
				'mod_block_id'	=> '0',
				'is_static'		=> '0',
				'block_cache_time'	=> '600',
			],
			[
				'ndx'			=> '2',
				'title'			=> 'Sub_Menu',
				'position'		=> 'L',
				'type'			=> 'H',
				'active'		=> '1',
				'html_file_name'=> 'block_menus_sub.html',
				'var_file_name'	=> '',
				'img_file_name'	=> 'sub_menu.png',
				'view_all'		=> '1',
				'view_groups'	=> '0',
				'view_pages'	=> '1,2,3,4,5,6,7,8,9,11,12,13,14',
				'groups'		=> '0',
				'scroll'		=> '0',
				'block_height'	=> '0',
				'has_vars'		=> '0',
				'minimod_based'	=> '0',
				'mod_block_id'	=> '0',
				'is_static'		=> '0',
				'block_cache_time'	=> '600',
			],
			[
				'ndx'			=> '3',
				'title'			=> 'Links_Menu',
				'position'		=> 'L',
				'type'			=> 'H',
				'active'		=> '1',
				'html_file_name'=> 'block_menus_links.html',
				'var_file_name'	=> '',
				'img_file_name'	=> 'sub_menu.png',
				'view_all'		=> '1',
				'view_groups'	=> '0',
				'view_pages'	=> '1,2,3,4,5,6,7,8,9,11,12,13,14',
				'groups'		=> '0',
				'scroll'		=> '0',
				'block_height'	=> '0',
				'has_vars'		=> '0',
				'minimod_based'	=> '0',
				'mod_block_id'	=> '0',
				'is_static'		=> '0',
				'block_cache_time'	=> '600',
			],
			[
				'ndx'			=> '4',
				'title'			=> 'Online Users',
				'position'		=> 'L',
				'type'			=> 'H',
				'active'		=> '1',
				'html_file_name'=> 'block_online_users.html',
				'var_file_name'	=> '',
				'img_file_name'	=> 'online_users.png',
				'view_all'		=> '1',
				'view_groups'	=> '0',
				'view_pages'	=> '1,2,3,4,5,6,7,8,9',
				'groups'		=> '0',
				'scroll'		=> '0',
				'block_height'	=> '0',
				'has_vars'		=> '0',
				'minimod_based'	=> '0',
				'mod_block_id'	=> '0',
				'is_static'		=> '0',
				'block_cache_time'	=> '600',
			],
			[
				'ndx'			=> '5',
				'title'			=> 'Last Online',
				'position'		=> 'L',
				'type'			=> 'H',
				'active'		=> '1',
				'html_file_name'=> 'block_last_online.html',
				'var_file_name'	=> 'k_last_online_vars.html',
				'img_file_name'	=> 'last_online.png',
				'view_all'		=> '1',
				'view_groups'	=> '0',
				'view_pages'	=> '2,3,4,5,6,7,8,9',
				'groups'		=> '0',
				'scroll'		=> '0',
				'block_height'	=> '0',
				'has_vars'		=> '1',
				'minimod_based'	=> '0',
				'mod_block_id'	=> '0',
				'is_static'		=> '0',
				'block_cache_time'	=> '300',
			],
			[
				'ndx'			=> '6',
				'title'			=> 'Search',
				'position'		=> 'L',
				'type'			=> 'H',
				'active'		=> '1',
				'html_file_name'=> 'block_search.html',
				'var_file_name'	=> '',
				'img_file_name'	=> 'search.png',
				'view_all'		=> '1',
				'view_groups'	=> '0',
				'view_pages'	=> '2,3,4,5,6,7,12',
				'groups'		=> '0',
				'scroll'		=> '0',
				'block_height'	=> '0',
				'has_vars'		=> '0',
				'minimod_based'	=> '0',
				'mod_block_id'	=> '0',
				'is_static'		=> '0',
				'block_cache_time'	=> '600',
			],
			[
				'ndx'			=> '7',
				'title'			=> 'Categories',
				'position'		=> 'L',
				'type'			=> 'H',
				'active'		=> '1',
				'html_file_name'=> 'block_forum_categories.html',
				'var_file_name'	=> '',
				'img_file_name'	=> 'categories.png',
				'view_all'		=> '1',
				'view_groups'	=> '0',
				'view_pages'	=> '2',
				'groups'		=> '0',
				'scroll'		=> '0',
				'block_height'	=> '0',
				'has_vars'		=> '0',
				'minimod_based'	=> '0',
				'mod_block_id'	=> '0',
				'is_static'		=> '0',
				'block_cache_time'	=> '667',
			],
			[
				'ndx'			=> '2',
				'title'			=> 'Welcome',
				'position'		=> 'C',
				'type'			=> 'H',
				'active'		=> '1',
				'html_file_name'=> 'block_welcome.html',
				'var_file_name'	=> 'k_welcome_vars.html',
				'img_file_name'	=> 'welcome.png',
				'view_all'		=> '1',
				'view_groups'	=> '0',
				'view_pages'	=> '2',
				'groups'		=> '0',
				'scroll'		=> '0',
				'block_height'	=> '0',
				'has_vars'		=> '1',
				'minimod_based'	=> '0',
				'mod_block_id'	=> '0',
				'is_static'		=> '0',
				'block_cache_time'	=> '999',
			],
			[
				'ndx'			=> '3',
				'title'			=> 'Announcements',
				'position'		=> 'C',
				'type'			=> 'H',
				'active'		=> '1',
				'html_file_name'=> 'block_announcements.html',
				'var_file_name'	=> 'k_announce_vars.html',
				'img_file_name'	=> 'announce.png',
				'view_all'		=> '1',
				'view_groups'	=> '0',
				'view_pages'	=> '2',
				'groups'		=> '0',
				'scroll'		=> '0',
				'block_height'	=> '0',
				'has_vars'		=> '1',
				'minimod_based'	=> '0',
				'mod_block_id'	=> '0',
				'is_static'		=> '0',
				'block_cache_time'	=> '300',
			],
			[
				'ndx'			=> '4',
				'title'			=> 'Recent Topics',
				'position'		=> 'C',
				'type'			=> 'H',
				'active'		=> '1',
				'html_file_name'=> 'block_recent_topics_wide.html',
				'var_file_name'	=> 'k_recent_topics_vars.html',
				'img_file_name'	=> 'recent_topics.png',
				'view_all'		=> '1',
				'view_groups'	=> '0',
				'view_pages'	=> '2',
				'groups'		=> '0',
				'scroll'		=> '0',
				'block_height'	=> '200',
				'has_vars'		=> '1',
				'minimod_based'	=> '0',
				'mod_block_id'	=> '0',
				'is_static'		=> '0',
				'block_cache_time'	=> '20',
			],
			[
				'ndx'			=> '5',
				'title'			=> 'News Report',
				'position'		=> 'C',
				'type'			=> 'H',
				'active'		=> '1',
				'html_file_name'=> 'block_news.html',
				'var_file_name'	=> 'k_news_vars.html',
				'img_file_name'	=> 'news.png',
				'view_all'		=> '1',
				'view_groups'	=> '0',
				'view_pages'	=> '2',
				'groups'		=> '0',
				'scroll'		=> '0',
				'block_height'	=> '0',
				'has_vars'		=> '1',
				'minimod_based'	=> '0',
				'mod_block_id'	=> '0',
				'is_static'		=> '0',
				'block_cache_time'	=> '50',
			],
			[
				'ndx'			=> '1',
				'title'			=> 'User Information',
				'position'		=> 'R',
				'type'			=> 'H',
				'active'		=> '1',
				'html_file_name'=> 'block_user_information.html',
				'var_file_name'	=> 'k_user_information_vars.html',
				'img_file_name'	=> 'user.png',
				'view_all'		=> '1',
				'view_groups'	=> '0',
				'view_pages'	=> '2,5,8,9',
				'groups'		=> '0',
				'scroll'		=> '0',
				'block_height'	=> '0',
				'has_vars'		=> '1',
				'minimod_based'	=> '0',
				'mod_block_id'	=> '0',
				'is_static'		=> '0',
				'block_cache_time'	=> '600',
			],
			[
				'ndx'			=> '2',
				'title'			=> 'The Team',
				'position'		=> 'R',
				'type'			=> 'H',
				'active'		=> '1',
				'html_file_name'=> 'block_the_teams.html',
				'var_file_name'	=> 'k_the_teams_vars.html',
				'img_file_name'	=> 'team.png',
				'view_all'		=> '1',
				'view_groups'	=> '0',
				'view_pages'	=> '2,5,8,9',
				'groups'		=> '0',
				'scroll'		=> '0',
				'block_height'	=> '0',
				'has_vars'		=> '1',
				'minimod_based'	=> '0',
				'mod_block_id'	=> '0',
				'is_static'		=> '0',
				'block_cache_time'	=> '555',
			],
			[
				'ndx'			=> '3',
				'title'			=> 'Top Posters',
				'position'		=> 'R',
				'type'			=> 'H',
				'active'		=> '1',
				'html_file_name'=> 'block_top_posters.html',
				'var_file_name'	=> 'k_top_posters_vars.html',
				'img_file_name'	=> 'rating.png',
				'view_all'		=> '1',
				'view_groups'	=> '0',
				'view_pages'	=> '2,5,8,9',
				'groups'		=> '0',
				'scroll'		=> '0',
				'block_height'	=> '0',
				'has_vars'		=> '1',
				'minimod_based'	=> '0',
				'mod_block_id'	=> '0',
				'is_static'		=> '0',
				'block_cache_time'	=> '200',
			],
			[
				'ndx'			=> '4',
				'title'			=> 'Most Active Topics',
				'position'		=> 'R',
				'type'			=> 'H',
				'active'		=> '1',
				'html_file_name'=> 'block_top_topics.html',
				'var_file_name'	=> 'k_top_topics_vars.html',
				'img_file_name'	=> 'most_active_topics.png',
				'view_all'		=> '1',
				'view_groups'	=> '0',
				'view_pages'	=> '2',
				'groups'		=> '0',
				'scroll'		=> '0',
				'block_height'	=> '0',
				'has_vars'		=> '1',
				'minimod_based'	=> '0',
				'mod_block_id'	=> '0',
				'is_static'		=> '0',
				'block_cache_time'	=> '100',
			],
			[
				'ndx'			=> '5',
				'title'			=> 'Clock',
				'position'		=> 'R',
				'type'			=> 'H',
				'active'		=> '1',
				'html_file_name'=> 'block_clock.html',
				'var_file_name'	=> '',
				'img_file_name'	=> 'clock.gif',
				'view_all'		=> '1',
				'view_groups'	=> '0',
				'view_pages'	=> '2,12,13,14',
				'groups'		=> '0',
				'scroll'		=> '0',
				'block_height'	=> '0',
				'has_vars'		=> '0',
				'minimod_based'	=> '0',
				'mod_block_id'	=> '0',
				'is_static'		=> '0',
				'block_cache_time'	=> '6009',
			],
			[
				'ndx'			=> '6',
				'title'			=> 'Links',
				'position'		=> 'R',
				'type'			=> 'H',
				'active'		=> '0',
				'html_file_name'=> 'block_links.html',
				'var_file_name'	=> 'k_links_vars.html',
				'img_file_name'	=> 'www.gif',
				'view_all'		=> '1',
				'view_groups'	=> '0',
				'view_pages'	=> '2,5,8,9,12',
				'groups'		=> '0',
				'scroll'		=> '1',
				'block_height'	=> '0',
				'has_vars'		=> '1',
				'minimod_based'	=> '0',
				'mod_block_id'	=> '0',
				'is_static'		=> '0',
				'block_cache_time'	=> '668',
			],
		];
		$this->db->sql_multi_insert($this->table_prefix . 'k_blocks', $blocks_sql);

		$menus_sql = [
			[
				'ndx'			=> '1',
				'menu_type'		=> '1',
				'name'			=> 'Main Menu',
				'link_to'		=> '',
				'extern'		=> '0',
				'append_sid'	=> '0',
				'append_uid'	=> '0',
				'menu_icon'		=> 'default.png',
				'view_all'		=> '1',
				'view_groups'	=> '',
				'soft_hr'		=> '0',
				'sub_heading'	=> '1',
			],
			[
				'ndx'			=> '2',
				'menu_type'		=> '1',
				'name'			=> 'Portal',
				'link_to'		=> 'portal.php',
				'extern'		=> '0',
				'append_sid'	=> '0',
				'append_uid'	=> '0',
				'menu_icon'		=> 'portal.png',
				'view_all'		=> '1',
				'view_groups'	=> '',
				'soft_hr'		=> '0',
				'sub_heading'	=> '0',
			],
			[
				'ndx'			=> '3',
				'menu_type'		=> '1',
				'name'			=> 'Forum',
				'link_to'		=> 'index.php',
				'extern'		=> '0',
				'append_sid'	=> '0',
				'append_uid'	=> '0',
				'menu_icon'		=> 'home2.png',
				'view_all'		=> '1',
				'view_groups'	=> '',
				'soft_hr'		=> '0',
				'sub_heading'	=> '0',
			],
			[
				'ndx'			=> '4',
				'menu_type'		=> '1',
				'name'			=> 'Navigator',
				'link_to'		=> '',
				'extern'		=> '0',
				'append_sid'	=> '0',
				'append_uid'	=> '0',
				'menu_icon'		=> 'default.png',
				'view_all'		=> '1',
				'view_groups'	=> '',
				'soft_hr'		=> '0',
				'sub_heading'	=> '1',
			],
			[
				'ndx'			=> '5',
				'menu_type'		=> '99',
				'name'			=> 'Album',
				'link_to'		=> 'inprogress.php',
				'extern'		=> '0',
				'append_sid'	=> '0',
				'append_uid'	=> '0',
				'menu_icon'		=> 'gallery.png',
				'view_all'		=> '0',
				'view_groups'	=> '',
				'soft_hr'		=> '0',
				'sub_heading'	=> '0',
			],
			[
				'ndx'			=> '6',
				'menu_type'		=> '1',
				'name'			=> 'Bookmarks',
				'link_to'		=> 'ucp.php?i=main&amp;mode=bookmarks',
				'extern'		=> '0',
				'append_sid'	=> '0',
				'append_uid'	=> '0',
				'menu_icon'		=> 'bookmark.png',
				'view_all'		=> '0',
				'view_groups'	=> '',
				'soft_hr'		=> '0',
				'sub_heading'	=> '0',
			],
			[
				'ndx'			=> '7',
				'menu_type'		=> '99',
				'name'			=> 'Downloads',
				'link_to'		=> 'inprogress.php',
				'extern'		=> '0',
				'append_sid'	=> '0',
				'append_uid'	=> '0',
				'menu_icon'		=> 'ff.png',
				'view_all'		=> '0',
				'view_groups'	=> '',
				'soft_hr'		=> '0',
				'sub_heading'	=> '0',
			],
			[
				'ndx'			=> '8',
				'menu_type'		=> '99',
				'name'			=> 'Links',
				'link_to'		=> 'inprogress.php',
				'extern'		=> '0',
				'append_sid'	=> '0',
				'append_uid'	=> '0',
				'menu_icon'		=> 'link.gif',
				'view_all'		=> '0',
				'view_groups'	=> '',
				'soft_hr'		=> '0',
				'sub_heading'	=> '0',
			],
			[
				'ndx'			=> '9',
				'menu_type'		=> '1',
				'name'			=> 'Members',
				'link_to'		=> 'memberlist.php',
				'extern'		=> '0',
				'append_sid'	=> '0',
				'append_uid'	=> '0',
				'menu_icon'		=> 'chat.png',
				'view_all'		=> '0',
				'view_groups'	=> '',
				'soft_hr'		=> '0',
				'sub_heading'	=> '0',
			],
			[
				'ndx'			=> '10',
				'menu_type'		=> '99',
				'name'			=> 'Ratings',
				'link_to'		=> 'index.php',
				'extern'		=> '0',
				'append_sid'	=> '0',
				'append_uid'	=> '0',
				'menu_icon'		=> 'rating.png',
				'view_all'		=> '0',
				'view_groups'	=> '',
				'soft_hr'		=> '0',
				'sub_heading'	=> '0',
			],
			[
				'ndx'			=> '11',
				'menu_type'		=> '1',
				'name'			=> 'Rules',
				'link_to'		=> 'rules.php',
				'extern'		=> '0',
				'append_sid'	=> '0',
				'append_uid'	=> '0',
				'menu_icon'		=> 'rules.png',
				'view_all'		=> '1',
				'view_groups'	=> '',
				'soft_hr'		=> '0',
				'sub_heading'	=> '0',
			],
			[
				'ndx'			=> '12',
				'menu_type'		=> '1',
				'name'			=> 'Staff',
				'link_to'		=> 'memberlist.php?mode=leaders',
				'extern'		=> '0',
				'append_sid'	=> '0',
				'append_uid'	=> '0',
				'menu_icon'		=> 'staff.png',
				'view_all'		=> '0',
				'view_groups'	=> '',
				'soft_hr'		=> '0',
				'sub_heading'	=> '0',
			],
			[
				'ndx'			=> '13',
				'menu_type'		=> '99',
				'name'			=> 'Statistics',
				'link_to'		=> 'inprogress.php',
				'extern'		=> '0',
				'append_sid'	=> '0',
				'append_uid'	=> '0',
				'menu_icon'		=> 'pie.png',
				'view_all'		=> '0',
				'view_groups'	=> '',
				'soft_hr'		=> '0',
				'sub_heading'	=> '0',
			],
			[
				'ndx'			=> '14',
				'menu_type'		=> '1',
				'name'			=> 'UCP',
				'link_to'		=> 'ucp.php',
				'extern'		=> '0',
				'append_sid'	=> '0',
				'append_uid'	=> '0',
				'menu_icon'		=> 'links.gif',
				'view_all'		=> '0',
				'view_groups'	=> '',
				'soft_hr'		=> '0',
				'sub_heading'	=> '0',
			],
			[
				'ndx'			=> '15',
				'menu_type'		=> '99',
				'name'			=> 'Chat',
				'link_to'		=> 'chat/index.php',
				'extern'		=> '0',
				'append_sid'	=> '0',
				'append_uid'	=> '0',
				'menu_icon'		=> 'chat.png',
				'view_all'		=> '0',
				'view_groups'	=> '',
				'soft_hr'		=> '0',
				'sub_heading'	=> '0',
			],
			[
				'ndx'			=> '16',
				'menu_type'		=> '1',
				'name'			=> 'Admin Menu',
				'link_to'		=> '',
				'extern'		=> '0',
				'append_sid'	=> '0',
				'append_uid'	=> '0',
				'menu_icon'		=> 'default.png',
				'view_all'		=> '0',
				'view_groups'	=> '',
				'soft_hr'		=> '0',
				'sub_heading'	=> '1',
			],
			[
				'ndx'			=> '17',
				'menu_type'		=> '1',
				'name'			=> 'Admin CP',
				'link_to'		=> 'adm/index.php',
				'extern'		=> '0',
				'append_sid'	=> '1',
				'append_uid'	=> '0',
				'menu_icon'		=> 'acp.png',
				'view_all'		=> '0',
				'view_groups'	=> '',
				'soft_hr'		=> '0',
				'sub_heading'	=> '0',
			],
			[
				'ndx'			=> '1',
				'menu_type'		=> '2',
				'name'			=> 'Mini Menu',
				'link_to'		=> '',
				'extern'		=> '0',
				'append_sid'	=> '0',
				'append_uid'	=> '0',
				'menu_icon'		=> 'default.png',
				'view_all'		=> '1',
				'view_groups'	=> '',
				'soft_hr'		=> '0',
				'sub_heading'	=> '1',
			],
			[
				'ndx'			=> '2',
				'menu_type'		=> '2',
				'name'			=> 'Active Posts',
				'link_to'		=> 'search.php?search_id=active_topics',
				'extern'		=> '0',
				'append_sid'	=> '0',
				'append_uid'	=> '0',
				'menu_icon'		=> 'links.png',
				'view_all'		=> '1',
				'view_groups'	=> '',
				'soft_hr'		=> '0',
				'sub_heading'	=> '0',
			],
			[
				'ndx'			=> '1',
				'menu_type'		=> '5',
				'name'			=> 'Lnks Menu',
				'link_to'		=> '',
				'extern'		=> '0',
				'append_sid'	=> '0',
				'append_uid'	=> '0',
				'menu_icon'		=> 'default.png',
				'view_all'		=> '1',
				'view_groups'	=> '',
				'soft_hr'		=> '0',
				'sub_heading'	=> '1',
			],
			[
				'ndx'			=> '2',
				'menu_type'		=> '5',
				'name'			=> 'Kiss Portal dev. site',
				'link_to'		=> 'http://www.phpbbireland.com',
				'extern'		=> '1',
				'append_sid'	=> '0',
				'append_uid'	=> '0',
				'menu_icon'		=> 'phpireland_globe.gif',
				'view_all'		=> '1',
				'view_groups'	=> '',
				'soft_hr'		=> '0',
				'sub_heading'	=> '0',
			],
			[
				'ndx'			=> '3',
				'menu_type'		=> '5',
				'name'			=> 'Stargate Portal',
				'link_to'		=> 'http://www.stargate-portal.com',
				'extern'		=> '1',
				'append_sid'	=> '0',
				'append_uid'	=> '0',
				'menu_icon'		=> 'phpireland_globe.gif',
				'view_all'		=> '1',
				'view_groups'	=> '',
				'soft_hr'		=> '0',
				'sub_heading'	=> '0',
			],
			[
				'ndx'			=> '4',
				'menu_type'		=> '5',
				'name'			=> 'phpBB3',
				'link_to'		=> 'http://www.phpbb.com',
				'extern'		=> '1',
				'append_sid'	=> '0',
				'append_uid'	=> '0',
				'menu_icon'		=> 'phpireland_globe.gif',
				'view_all'		=> '1',
				'view_groups'	=> '',
				'soft_hr'		=> '0',
				'sub_heading'	=> '0',
			],
		];
		$this->db->sql_multi_insert($this->table_prefix . 'k_menus', $menus_sql);

		$resources_sql = [
			[
				'word'	=> 'phpBB',
				'type'	=> 'R',
			],
			[
				'word'	=> '{PORTAL_VERSION}',
				'type'	=> 'V',
			],
			[
				'word'	=> '{PORTAL_BUILD}',
				'type'	=> 'V',
			],
			[
				'word'	=> '{VERSION}',
				'type'	=> 'V',
			],
			[
				'word'	=> '{SITENAME}',
				'type'	=> 'V',
			],
		];
		$this->db->sql_multi_insert($this->table_prefix . 'k_resources', $resources_sql);

		$pages_sql = [
			[
				'page_name'	=> 'index',
			],
			[
				'page_name'	=> 'portal',
			],
			[
				'page_name'	=> 'viewforum',
			],
			[
				'page_name'	=> 'viewtopic',
			],
			[
				'page_name'	=> 'memberlist',
			],
			[
				'page_name'	=> 'mcp',
			],
			[
				'page_name'	=> 'ucp',
			],
			[
				'page_name'	=> 'search',
			],
			[
				'page_name'	=> 'faq',
			],
			[
				'page_name'	=> 'posting',
			],
		];
		$this->db->sql_multi_insert($this->table_prefix . 'k_pages', $pages_sql);

		$vars_sql = [
			[
				'config_name'	=> 'k_announce_allow',
				'config_value'	=> '1',
			],
			[
				'config_name'	=> 'k_allow_acronyms',
				'config_value'	=> '1',
			],
			[
				'config_name'	=> 'k_bot_display_allow',
				'config_value'	=> '1',
			],
			[
				'config_name'	=> 'k_footer_images_allow',
				'config_value'	=> '1',
			],
			[
				'config_name'	=> 'k_news_allow',
				'config_value'	=> '1',
			],
			[
				'config_name'	=> 'k_announce_type',
				'config_value'	=> '0',
			],
			[
				'config_name'	=> 'k_blocks_display_globally',
				'config_value'	=> '1',
			],
			[
				'config_name'	=> 'k_smilies_show',
				'config_value'	=> '1',
			],
			[
				'config_name'	=> 'k_links_scroll_amount',
				'config_value'	=> '0',
			],
			[
				'config_name'	=> 'k_links_scroll_direction',
				'config_value'	=> '0',
			],
			[
				'config_name'	=> 'k_announce_item_max_length',
				'config_value'	=> '400',
			],
			[
				'config_name'	=> 'k_news_item_max_length',
				'config_value'	=> '350',
			],
			[
				'config_name'	=> 'k_last_online_max',
				'config_value'	=> '10',
			],
			[
				'config_name'	=> 'k_news_type',
				'config_value'	=> '0',
			],
			[
				'config_name'	=> 'k_announce_to_display',
				'config_value'	=> '5',
			],
			[
				'config_name'	=> 'k_links_to_display',
				'config_value'	=> '5',
			],
			[
				'config_name'	=> 'k_links_forum_id',
				'config_value'	=> '',
			],
			[
				'config_name'	=> 'k_news_items_to_display',
				'config_value'	=> '5',
			],
			[
				'config_name'	=> 'k_recent_topics_to_display',
				'config_value'	=> '25',
			],
			[
				'config_name'	=> 'k_recent_topics_per_forum',
				'config_value'	=> '5',
			],
			[
				'config_name'	=> 'k_top_posters_to_display',
				'config_value'	=> '10',
			],
			[
				'config_name'	=> 'k_top_posters_show',
				'config_value'	=> '1',
			],
			[
				'config_name'	=> 'k_recent_search_days',
				'config_value'	=> '7',
			],
			[
				'config_name'	=> 'k_allow_rotating_logos',
				'config_value'	=> '1',
			],
			[
				'config_name'	=> 'k_post_types',
				'config_value'	=> '1',
			],
			[
				'config_name'	=> 'k_top_topics_max',
				'config_value'	=> '5',
			],
			[
				'config_name'	=> 'k_adm_block',
				'config_value'	=> '',
			],
			[
				'config_name'	=> 'k_quick_reply',
				'config_value'	=> '1',
			],
			[
				'config_name'	=> 'k_recent_topics_search_exclude',
				'config_value'	=> '',
			],
			[
				'config_name'	=> 'k_top_topics_days',
				'config_value'	=> '7',
			],
			[
				'config_name'	=> 'k_block_cache_time_default',
				'config_value'	=> '600',
			],
			[
				'config_name'	=> 'k_block_cache_time_short',
				'config_value'	=> '10',
			],
			[
				'config_name'	=> 'k_teams',
				'config_value'	=> '',
			],
			[
				'config_name'	=> 'k_teams_display_this_many',
				'config_value'	=> '2',
			],
			[
				'config_name'	=> 'k_max_block_avatar_width',
				'config_value'	=> '80',
			],
			[
				'config_name'	=> 'k_max_block_avatar_height',
				'config_value'	=> '80',
			],
			[
				'config_name'	=> 'k_teampage_memberships',
				'config_value'	=> '0',
			],
			[
				'config_name'	=> 'k_tooltips_active',
				'config_value'	=> '1',
			],
			[
				'config_name'	=> 'k_tooltips_which',
				'config_value'	=> '1',
			],
			[
				'config_name'	=> 'k_landing_page',
				'config_value'	=> 'portal',
			],
			[
				'config_name'	=> 'k_mod_folders',
				'config_value'	=> '',
			],
			[
				'config_name'	=> 'k_teams_sort',
				'config_value'	=> 'default',
			],

		];
		$this->db->sql_multi_insert($this->table_prefix . 'k_vars', $vars_sql);
	}
}
